### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by txya900619** [txya900619/LOZ-ALTTP#1]
- [ ] Object on map(grass) 
- [ ] HP/MP info UI
- [ ] How to show dialog box
- [ ] Rain Effect
- [ ] Entity death animation
- [ ] Entity drop heart
- [ ] Dungen map
- [ ] Dungen object
- [ ] Dungen keys and Door
- [ ] Render roof
- [ ] add BGM
- [ ] Save/Load system
- [ ] Auto save point
- [ ] Select save scene
- [ ] Drop system(?
